public class Screens implements ITuWas {

    Ausgabe Begrüßung;
    Taste Spielen;
    Taste Credits;
    Taste Optionen;
    Taste Shop;
    Taste Exit;
    Taste Achievements;
    Taste Sound;
    Taste Musik;
    Taste Hauptmenü;
    Taste Sound2;
    Taste Musik2;
    Ausgabe Options;
    Taste Anfang1;
    Taste Anfang2;
    Taste Anfang3;
    Taste Speed1;
    Taste Speed2;
    Taste Speed3;
    Taste Sprung1;
    Taste Sprung2;
    Taste Sprung3;
    Taste ges1;
    Taste ges2;
    Taste ges3;
    Ausgabe Shop2;
    Ausgabe Speed;
    Ausgabe ges;
    Ausgabe Anfang;
    Ausgabe Sprung;
    Kreis speed1;
    Kreis speed2;
    Kreis speed3;
    Kreis sprung1;
    Kreis sprung2;
    Kreis sprung3;
    Kreis Ges1;
    Kreis Ges2;
    Kreis Ges3;
    Kreis anfang1;
    Kreis anfang2;
    Kreis anfang3;

    void ZeigeHauptmenue(){
        Spielen= new Taste();
        Credits= new Taste();
        Optionen= new Taste();
        Shop= new Taste();
        Exit= new Taste();
        Achievements= new Taste();
        Begrüßung= new Ausgabe();
        Begrüßung.setzeAusgabetext("Herzlich Willkommen Bruchpilot beim Spiel Weitflug");
        Begrüßung.setzeAusrichtung(0);
        Begrüßung.setzePosition(400,0);
        Begrüßung.setzeFarbe("gruen");
        Begrüßung.setzeGroesse(600,100);
        Spielen.setzeDimensionen(500,100,200,50);
        Spielen.setzeAusgabetext("Spielen");
        Spielen.setzeHintergrundfarbe("lila");
        Optionen.setzeDimensionen(500,200,200,50);
        Optionen.setzeAusgabetext("Optionen");
        Optionen.setzeHintergrundfarbe("lila");
        Shop.setzeDimensionen(500,300,200,50);
        Shop.setzeAusgabetext("Shop");
        Shop.setzeHintergrundfarbe("lila");
        Achievements.setzeDimensionen(500,400,200,50);
        Achievements.setzeAusgabetext("Achievements");
        Achievements.setzeHintergrundfarbe("lila");
        Credits.setzeDimensionen(500,500,200,50);
        Credits.setzeAusgabetext("Credits");
        Credits.setzeHintergrundfarbe("lila");
        Exit.setzeDimensionen(500,600,200,50);
        Exit.setzeAusgabetext("Exit");
        Exit.setzeHintergrundfarbe("lila");
         Speed1.entfernen();
        Speed2.entfernen();
        Speed3.entfernen();
        Sprung1.entfernen();
        Sprung2.entfernen();
        Sprung3.entfernen();
        Anfang1.entfernen();
        Anfang2.entfernen();
        Anfang3.entfernen();
        ges1.entfernen();
        ges2.entfernen();
        ges3.entfernen();
        Sprung.entfernen();
        Anfang.entfernen();
        ges.entfernen();
        Speed.entfernen();
        speed1.entfernen();
        speed2.entfernen();
        speed3.entfernen();
        sprung1.entfernen();
        sprung2.entfernen();
        sprung3.entfernen();
        anfang1.entfernen();
        anfang2.entfernen();
        anfang3.entfernen();
        Ges1.entfernen();
        Ges2.entfernen();
        Ges3.entfernen();
        Options.entfernen();
        Sound.entfernen();
        Musik.entfernen();
        Sound2.entfernen();
        Musik2.entfernen();
        Hauptmenü.entfernen();

    }

    void zeigeOptionen(){
        Options= new Ausgabe();
        Sound= new Taste();
        Musik= new Taste();
        Sound2= new Taste();
        Musik2=new Taste();
        Hauptmenü= new Taste();
        Options.setzeDimensionen(500,0,200,20);
        Options.setzeAusgabetext("Optionen");
        Options.setzeFarbe("gruen");
        Sound.setzeDimensionen(375,100,200,50);
        Sound.setzeAusgabetext("Sound an");
        Sound.setzeHintergrundfarbe("lila");
        Musik.setzeDimensionen(375,175,200,50);
        Musik.setzeAusgabetext("Musik an");
        Musik.setzeHintergrundfarbe("lila");
        Hauptmenü.setzeDimensionen(500,250,200,50);
        Hauptmenü.setzeAusgabetext("Hauptmenü");
        Hauptmenü.setzeHintergrundfarbe("lila");
        Sound2.setzeDimensionen(625,100,200,50);
        Sound2.setzeAusgabetext("Sound aus");
        Musik2.setzeDimensionen(625,175,200,50);
        Musik2.setzeAusgabetext("Musik aus");
        Musik2.setzeHintergrundfarbe("lila");
        Sound2.setzeHintergrundfarbe("lila");
        Exit.entfernen();
        Credits.entfernen();
        Achievements.entfernen();
        Shop.entfernen();
        Optionen.entfernen();
        Spielen.entfernen();
        Begrüßung.entfernen();
        Speed1.entfernen();
        Speed2.entfernen();
        Speed3.entfernen();
        Sprung1.entfernen();
        Sprung2.entfernen();
        Sprung3.entfernen();
        Anfang1.entfernen();
        Anfang2.entfernen();
        Anfang3.entfernen();
        ges1.entfernen();
        ges2.entfernen();
        ges3.entfernen();
        Sprung.entfernen();
        Anfang.entfernen();
        ges.entfernen();
        Speed.entfernen();
        speed1.entfernen();
        speed2.entfernen();
        speed3.entfernen();
        sprung1.entfernen();
        sprung2.entfernen();
        sprung3.entfernen();
        anfang1.entfernen();
        anfang2.entfernen();
        anfang3.entfernen();
        Ges1.entfernen();
        Ges2.entfernen();
        Ges3.entfernen();

    }

    void zeigeShop(){
        Hauptmenü= new Taste();
        Speed1= new Taste();
        Speed2= new Taste();
        Speed3= new Taste();
        Sprung1= new Taste();
        Sprung2= new Taste();
        Sprung3= new Taste();
        Anfang1= new Taste();
        Anfang2= new Taste();
        Anfang3= new Taste();
        ges1= new Taste();
        ges2= new Taste();
        ges3= new Taste();
        Shop2= new Ausgabe();
        Sprung= new Ausgabe();
        Speed= new Ausgabe();
        Anfang= new Ausgabe();
        ges= new Ausgabe();
        speed1= new Kreis();
        speed2= new Kreis();
        speed3= new Kreis();
        sprung1= new Kreis();
        sprung2= new Kreis();
        sprung3= new Kreis();
        Ges1= new Kreis();
        Ges2= new Kreis();
        Ges3= new Kreis();
        anfang1= new Kreis();
        anfang2= new Kreis();
        anfang3= new Kreis();
        Hauptmenü.setzeDimensionen(550,500,200,50);
        Hauptmenü.setzeAusgabetext("Hauptmenü");
        Hauptmenü.setzeHintergrundfarbe("orange");
        speed1.setzeDimensionen(310,150,20);
        speed2.setzeDimensionen(310,250,20);
        speed3.setzeDimensionen(310,350,20);
        Speed1.setzeDimensionen(100,150,200,50);
        Speed2.setzeDimensionen(100,250,200,50);
        Speed3.setzeDimensionen(100,350,200,50);
        sprung1.setzeDimensionen(610,150,20);
        sprung2.setzeDimensionen(610,250,20);
        sprung3.setzeDimensionen(610,350,20);
        Sprung1.setzeDimensionen(400,150,200,50);
        Sprung2.setzeDimensionen(400,250,200,50);
        Sprung3.setzeDimensionen(400,350,200,50);
        anfang1.setzeDimensionen(910,150,20);
        anfang2.setzeDimensionen(910,250,20);
        anfang3.setzeDimensionen(910,350,20);
        Anfang1.setzeDimensionen(700,150,200,50);
        Anfang2.setzeDimensionen(700,250,200,50);
        Anfang3.setzeDimensionen(700,350,200,50);
        Ges1.setzeDimensionen(1210,150,20);
        Ges2.setzeDimensionen(1210,250,20);
        Ges3.setzeDimensionen(1210,350,20);
        anfang1.setzeFarbe("rot");
        anfang2.setzeFarbe("rot");
        anfang3.setzeFarbe("rot");
        speed1.setzeFarbe("rot");
        speed2.setzeFarbe("rot");
        speed3.setzeFarbe("rot");
        Ges1.setzeFarbe("rot");
        Ges2.setzeFarbe("rot");
        Ges3.setzeFarbe("rot");
        sprung1.setzeFarbe("rot");
        sprung2.setzeFarbe("rot");
        sprung3.setzeFarbe("rot");
        ges1.setzeDimensionen(1000,150,200,50);
        ges2.setzeDimensionen(1000,250,200,50);
        ges3.setzeDimensionen(1000,350,200,50);
        Shop2.setzePosition(630,0);
        Shop2.setzeAusrichtung(0);
        Speed.setzePosition(100,50);
        Sprung.setzePosition(400,50);
        Anfang.setzePosition(700,50);
        ges.setzePosition(1000,50);
        Speed.setzeGroesse(200,100);
        Anfang.setzeGroesse(200,100);
        ges.setzeGroesse(200,100);
        Sprung.setzeGroesse(200,100);
        Shop2.setzeAusgabetext("Shop");
        Speed.setzeAusgabetext("Speedboost");
        Sprung.setzeAusgabetext("Sprungboost");
        Anfang.setzeAusgabetext("Startboost");
        ges.setzeAusgabetext("Ges. Steigerung");
        Speed1.setzeAusgabetext("Steigerung 1");
        Speed2.setzeAusgabetext("Steigerung 2");
        Speed3.setzeAusgabetext("Steigerung 3");
        Anfang1.setzeAusgabetext("Steigerung 1");
        Anfang2.setzeAusgabetext("Steigerung 2");
        Anfang3.setzeAusgabetext("Steigerung 3");
        ges1.setzeAusgabetext("Steigerung 1");
        ges2.setzeAusgabetext("Steigerung 2");
        ges3.setzeAusgabetext("Steigerung 3");
        Sprung1.setzeAusgabetext("Steigerung 1");
        Sprung2.setzeAusgabetext("Steigerung 2");
        Sprung3.setzeAusgabetext("Steigerung 3");
        Shop2.setzeFarbe("gruen");
        Speed.setzeFarbe("rot");
        Anfang.setzeFarbe("blau");
        ges.setzeFarbe("gelb");
        Sprung.setzeFarbe("lila");
        Options.entfernen();
        Sound.entfernen();
        Musik.entfernen();
        Sound2.entfernen();
        Musik2.entfernen();
        Exit.entfernen();
        Credits.entfernen();
        Achievements.entfernen();
        Shop.entfernen();
        Optionen.entfernen();
        Spielen.entfernen();
        Begrüßung.entfernen();
        

    }

    public void tuWas(int id){
    }
}